## 1. Introduction
<p>Everyone loves Lego (unless you ever stepped on one). Did you know by the way that "Lego" was derived from the Danish phrase leg godt, which means "play well"? Unless you speak Danish, probably not. </p>
<p>In this project, we will analyze a fascinating dataset on every single lego block that has ever been built!</p>
<p><img src="https://s3.amazonaws.com/assets.datacamp.com/production/project_10/datasets/lego-bricks.jpeg" alt="lego"></p>

In [90]:
# Nothing to do here

## 2. Reading Data
<p>A comprehensive database of lego blocks is provided by <a href="https://rebrickable.com/downloads/">Rebrickable</a>. The data is available as csv files and the schema is shown below.</p>
<p><img src="https://s3.amazonaws.com/assets.datacamp.com/production/project_10/datasets/downloads_schema.png" alt="schema"></p>
<p>Let us start by reading in the colors data to get a sense of the diversity of lego sets!</p>

In [92]:
# Import modules
import pandas as pd

# Read colors data
colors = pd.read_csv('datasets/colors.csv')

# Print the first few rows
colors.head()

   id            name     rgb is_trans
0  -1         Unknown  0033B2        f
1   0           Black  05131D        f
2   1            Blue  0055BF        f
3   2           Green  237841        f
4   3  Dark Turquoise  008F9B        f

## 3. Exploring Colors
<p>Now that we have read the <code>colors</code> data, we can start exploring it! Let us start by understanding the number of colors available.</p>

In [94]:
# How many distinct colors are available?
num_colors = colors.shape
num_colors = num_colors[0]
num_colors

135

## 4. Transparent Colors in Lego Sets
<p>The <code>colors</code> data has a column named <code>is_trans</code> that indicates whether a color is transparent or not. It would be interesting to explore the distribution of transparent vs. non-transparent colors.</p>

In [96]:
# colors_summary: Distribution of colors based on transparency
colors_summary = colors.groupby('is_trans').count()
colors_summary

           id  name  rgb
is_trans
f         107   107  107
t          28    28   28

## 5. Explore Lego Sets
<p>Another interesting dataset available in this database is the <code>sets</code> data. It contains a comprehensive list of sets over the years and the number of parts that each of these sets contained. </p>
<p><img src="https://imgur.com/1k4PoXs.png" alt="sets_data"></p>
<p>Let us use this data to explore how the average number of parts in Lego sets has varied over the years.</p>

In [98]:
%matplotlib inline
# Read sets data as `sets`
sets = pd.read_csv('datasets/sets.csv')
# Create a summary of average number of parts by year: `parts_by_year`
parts_by_year = sets.groupby('year').count()
parts_by_year

# Plot trends in average number of parts by year
#parts_by_year.plot(x = parts_by_year['year'], y = parts_by_year['num_parts'])

      set_num  name  theme_id  num_parts
year
1950        7     7         7          7
1953        4     4         4          4
1954       14    14        14         14
1955       28    28        28         28
1956       12    12        12         12
1957       21    21        21         21
1958       42    42        42         42
1959        4     4         4          4
1960        3     3         3          3
1961       17    17        17         17
1962       40    40        40         40
1963       18    18        18         18
1964       11    11        11         11
1965       10    10        10         10
1966       89    89        89         89
1967       21    21        21         21
1968       25    25        25         25
1969       69    69        69         69
1970       29    29        29         29
1971       45    45        45         45
1972       38    38        38         38
1973       68    68        68         68
1974       39    39        39         39
1975       31    31        31         31
1976       68    68        68         68
1977       92    92        92         92
1978       73    73        73         73
1979       82    82        82         82
1980       88    88        88         88
1981       79    79        79         79
...       ...   ...       ...        ...
1988       68    68        68         68
1989      114   114       114        114
1990       85    85        85         85
1991      106   106       106        106
1992      115   115       115        115
1993      111   111       111        111
1994      128   128       128        128
1995      128   128       128        128
1996      144   144       144        144
1997      194   194       194        194
1998      325   325       325        325
1999      300   300       300        300
2000      327   327       327        327
2001      339   339       339        339
2002      447   447       447        447
2003      415   415       415        415
2004      371   371       371        371
2005      330   330       330        330
2006      283   283       283        283
2007      319   319       319        319
2008      349   349       349        349
2009      403   403       403        403
2010      444   444       444        444
2011      502   502       502        502
2012      615   615       615        615
2013      593   593       593        593
2014      715   715       715        715
2015      670   670       670        670
2016      609   609       609        609
2017      470   470       470        470

[66 rows x 4 columns]

## 6. Lego Themes Over Years
<p>Lego blocks ship under multiple <a href="https://shop.lego.com/en-US/Themes">themes</a>. Let us try to get a sense of how the number of themes shipped has varied over the years.</p>

In [100]:
# themes_by_year: Number of themes shipped by year
themes_by_year = sets[[]]

## 7. Wrapping It All Up!
<p>Lego blocks offer an unlimited amount of fun across ages. We explored some interesting trends around colors, parts, and themes. </p>

In [102]:
# Nothing to do here